Editorial pass for examples
decentralized-identity/presentation-exchange pull request #187
Opened 2021-02-13 19:35 UTC by bumblefudge

Forgive me if I overstepped my remit (or my understanding) but I tried updating the examples in a couple different ways:
- Made the situations more realistic/concrete and updated `pattern` and `purpose` to match (hopefully in line with the intent of #169 )
- Added a few `limit_disclosure` properties per the updated situations and `purpose` props
- Fixed some date formatting and other minor editorial things while i was there
- Updated the LD example to have a RL2020 status object rather than the somewhat baffling boolean
- Tried to fix a link to the LDP spec on line 2158 (formerly line 2168)

2021-02-15 23:04 UTC, brentzundel approved these changes

2021-02-16 08:48 UTC, bumblefudge commented
fixed the merge conflict (Daniel removed the localization section while I was updating its example like a goof)

2021-02-16 19:03 UTC, brentzundel submitted a review, later dismissed

2021-02-18 17:21 UTC, rado0x54 commented
Uh, I should have definitely merged this PR in before doing my own :)

2021-02-18 17:23 UTC, rado0x54 commented
I would maybe propose to first merge #194. Because it contains the tests that can easily check for the example changes in this one. The other way around may be a little harder, but I can do that as well after the meeting.

2021-02-18 22:45 UTC, bumblefudge commented
I'm still a little confused where /test/presentation-submission/example.json is... which leaves me with the unsettling feeling I've made a clerical mistake somewhere 😬

2021-02-19 21:47 UTC, csuwildcat requested changes
Just need to get the final format tweak in for the replacer functionality, which looks like this:  `[[insert: ./test/presentation-definition/example.json]]`

2021-02-19 21:47 UTC, csuwildcat commented on spec/spec.md
> +[[import ../test/presentation-definition/example.json ]]
I ended up going with `insert`, and the path is assumed to be from the root of the project, so could you change this to : [[insert: ./test/presentation-definition/example.json]]?

2021-02-19 21:47 UTC, csuwildcat commented on spec/spec.md
> +[[import: ../test/presentation-definition/single_group_example.json]]
Same comment above, the form of this is going to be: [[insert: ./test/presentation-definition/single_group_example.json]]

2021-02-22 18:56 UTC, bumblefudge commented
@csuwildcat does [this](https://github.com/decentralized-identity/presentation-exchange/pull/187/commits/9990430d3c68304ac7bcd8d1fa17bcb0ca88be7b) scratch the itch you've requested?

2021-02-25 18:04 UTC, csuwildcat approved these changes

2021-02-25 18:04 UTC, merged