Link hackmd running agenda for BOTH PE and CM from repo
decentralized-identity/presentation-exchange pull request #282
Opened 2021-12-17 11:33 UTC by bumblefudge

2022-01-05 22:29 UTC, brentzundel approved these changes

2022-01-13 18:24 UTC, JaceHensley commented
Could we just have a link to the hackMD that way the we don't need to remember to update the contents in the repo each week?

2022-01-13 18:31 UTC, kimdhamilton requested changes
As @JaceHensley requested, please add link to hackmd instead

2022-01-25 23:47 UTC, bumblefudge commented
<ahem> this way, however clunky, is what DIF has been trying to align on since... summer 2020.  will put in an explanation

2022-03-24 19:13 UTC, merged